/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedAnimalsIndexRouteImport } from './routes/_authed/animals/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthedAnimalsIdRouteImport } from './routes/_authed/animals/$id'
import { Route as AuthedAdminLeaveTypesIndexRouteImport } from './routes/_authed/admin/leave-types/index'
import { Route as AuthedAdminLeaveTypesNewRouteImport } from './routes/_authed/admin/leave-types/new'
import { Route as AuthedAdminLeaveTypesIdRouteImport } from './routes/_authed/admin/leave-types/$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAnimalsIndexRoute = AuthedAnimalsIndexRouteImport.update({
  id: '/animals/',
  path: '/animals/',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedAnimalsIdRoute = AuthedAnimalsIdRouteImport.update({
  id: '/animals/$id',
  path: '/animals/$id',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminLeaveTypesIndexRoute =
  AuthedAdminLeaveTypesIndexRouteImport.update({
    id: '/admin/leave-types/',
    path: '/admin/leave-types/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedAdminLeaveTypesNewRoute =
  AuthedAdminLeaveTypesNewRouteImport.update({
    id: '/admin/leave-types/new',
    path: '/admin/leave-types/new',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedAdminLeaveTypesIdRoute = AuthedAdminLeaveTypesIdRouteImport.update({
  id: '/admin/leave-types/$id',
  path: '/admin/leave-types/$id',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/animals/$id': typeof AuthedAnimalsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/animals/': typeof AuthedAnimalsIndexRoute
  '/admin/leave-types/$id': typeof AuthedAdminLeaveTypesIdRoute
  '/admin/leave-types/new': typeof AuthedAdminLeaveTypesNewRoute
  '/admin/leave-types/': typeof AuthedAdminLeaveTypesIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AuthedIndexRoute
  '/animals/$id': typeof AuthedAnimalsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/animals': typeof AuthedAnimalsIndexRoute
  '/admin/leave-types/$id': typeof AuthedAdminLeaveTypesIdRoute
  '/admin/leave-types/new': typeof AuthedAdminLeaveTypesNewRoute
  '/admin/leave-types': typeof AuthedAdminLeaveTypesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/animals/$id': typeof AuthedAnimalsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_authed/animals/': typeof AuthedAnimalsIndexRoute
  '/_authed/admin/leave-types/$id': typeof AuthedAdminLeaveTypesIdRoute
  '/_authed/admin/leave-types/new': typeof AuthedAdminLeaveTypesNewRoute
  '/_authed/admin/leave-types/': typeof AuthedAdminLeaveTypesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/animals/$id'
    | '/api/auth/$'
    | '/animals/'
    | '/admin/leave-types/$id'
    | '/admin/leave-types/new'
    | '/admin/leave-types/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/animals/$id'
    | '/api/auth/$'
    | '/animals'
    | '/admin/leave-types/$id'
    | '/admin/leave-types/new'
    | '/admin/leave-types'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/_authed/'
    | '/_authed/animals/$id'
    | '/api/auth/$'
    | '/_authed/animals/'
    | '/_authed/admin/leave-types/$id'
    | '/_authed/admin/leave-types/new'
    | '/_authed/admin/leave-types/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/animals/': {
      id: '/_authed/animals/'
      path: '/animals'
      fullPath: '/animals/'
      preLoaderRoute: typeof AuthedAnimalsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/animals/$id': {
      id: '/_authed/animals/$id'
      path: '/animals/$id'
      fullPath: '/animals/$id'
      preLoaderRoute: typeof AuthedAnimalsIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/leave-types/': {
      id: '/_authed/admin/leave-types/'
      path: '/admin/leave-types'
      fullPath: '/admin/leave-types/'
      preLoaderRoute: typeof AuthedAdminLeaveTypesIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/leave-types/new': {
      id: '/_authed/admin/leave-types/new'
      path: '/admin/leave-types/new'
      fullPath: '/admin/leave-types/new'
      preLoaderRoute: typeof AuthedAdminLeaveTypesNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/leave-types/$id': {
      id: '/_authed/admin/leave-types/$id'
      path: '/admin/leave-types/$id'
      fullPath: '/admin/leave-types/$id'
      preLoaderRoute: typeof AuthedAdminLeaveTypesIdRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedAnimalsIdRoute: typeof AuthedAnimalsIdRoute
  AuthedAnimalsIndexRoute: typeof AuthedAnimalsIndexRoute
  AuthedAdminLeaveTypesIdRoute: typeof AuthedAdminLeaveTypesIdRoute
  AuthedAdminLeaveTypesNewRoute: typeof AuthedAdminLeaveTypesNewRoute
  AuthedAdminLeaveTypesIndexRoute: typeof AuthedAdminLeaveTypesIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedAnimalsIdRoute: AuthedAnimalsIdRoute,
  AuthedAnimalsIndexRoute: AuthedAnimalsIndexRoute,
  AuthedAdminLeaveTypesIdRoute: AuthedAdminLeaveTypesIdRoute,
  AuthedAdminLeaveTypesNewRoute: AuthedAdminLeaveTypesNewRoute,
  AuthedAdminLeaveTypesIndexRoute: AuthedAdminLeaveTypesIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
